baseURL = "https://saucewu.github.io/"
languageCode = "zh"
DefaultContentLanguage = "zh"
title = "Website of SauceWu "
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-166235531-1"

[params]
title = "Sauce Wu Blog"
author = "Sauce Wu"
profilePicture = "images/profile.jpeg"
keywords = ""
favicon = "favicons/"
customCss = []

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/SauceWu"


[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:sauce.wu@hotmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts"

